Ports CBT and updates TGUI, moves loadout to prefs
nokele/Fortune13 pull request #395
Opened 2021-07-18 06:34 UTC by Rohesie

Huge unatomic PR.
* Updates TGUI to latest /tg/ version.
* Ports the Common Build Tool.
* Moves the custom loadout to prefs. This implies a temporary regression of not being able to preview the uniform, until /tg/ adds TGUI prefs. Then it will be simpler to add it, with proper compatibility and better code than what was here.

![EuWJbP5pDr](https://user-images.githubusercontent.com/42041276/126058060-17d4a2af-3052-4323-9bba-4e4119b076c4.png)

2021-07-18 07:26 UTC, Tokorizo commented
god bless your valiant work

2021-07-18 09:09 UTC, EgorDinamit commented
We wish you good luck, we really needed it.

2021-07-19 16:16 UTC, Cyberboss requested changes

2021-07-19 16:16 UTC, Cyberboss commented on tools/build/build
> +#!/bin/sh
This file needs to be executable. Run `git update-index --chmod=+x tools/build/build`

2021-07-19 23:23 UTC, merged